config/routes.rb
Rails.application.routes.draw do
  resources :payment_requests, only: %i(index update)

  root "payment_requests#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/payment_request.rb
# frozen_string_literal: true

class PaymentRequest < ApplicationRecord
  validates :status, inclusion: { in: %w(pending accepted rejected) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/payment_requests_controller.rb
# frozen_string_literal: true

class PaymentRequestsController < ApplicationController
  def index
    @payment_requests = PaymentRequest.all.order(:id)
  end

  def update
    payment_request.update!(update_payment_request_params)
    EmitUpdatedPaymentRequestEvent.call(payment_request)
    redirect_to root_path, notice: "Payment request has been updated"
    rescue ActiveRecord::ActiveRecordError => e
      flash[:alert] = e.message
      render :index
  end

  private

  def payment_request
    @payment_request ||= PaymentRequest.find(params[:id])
  end

  def update_payment_request_params
    params.require(:payment_request).permit(:status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payment_requests/index.html.erb
<table>
  <tr>
    <th>Description</th>
    <th>Amount</th>
    <th>Currency</th>
    <th>Status</th>
    <th></th>
    <th></th>
  </tr>
  <% @payment_requests.each do |payment_request| %>
    <tr>
      <td><%= payment_request.description %></td>
      <td><%= payment_request.amount %></td>
      <td><%= payment_request.currency %></td>
      <td><%= payment_request.status %></td>
      <% if payment_request.status == "pending" %>
        <td><%= link_to "Accept", payment_request_path(payment_request, payment_request: { status: "accepted" }), method: :put %></td>
        <td><%= link_to "Decline", payment_request_path(payment_request, payment_request: { status: "rejected" }), method: :put %></td>
      <% end %>
    </tr>
  <% end %>
</table>